# Generated by Django 4.1.1 on 2022-09-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='econtract',
            new_name='econtact',
        ),
    ]
